from django.urls import path
from .views import (
    ProjectCreateView,
    PostUpdateView,
    listApprovedProjectsView,
    RetrieveProjectsView,
    listOrgProjectsView,
    PostMilestoneImages,
    MilestoneImagesRetrieveUpdateDestroyAPIView,
    MilestoneRetrieveView,
    ExpensesCreateView,
    CommentCreateView,
    CommentRetrieveUpdateDestroyView,
    listCommentsByProjectsView,
    MyProjectListView,
    MakeDonationsAPIView,
    ListDonationsView,
)

urlpatterns = [
    path('create/', ProjectCreateView.as_view()),
    path('', listApprovedProjectsView.as_view()),
    path('my-projects/', MyProjectListView.as_view()),
    path('<uuid:pk>/', RetrieveProjectsView.as_view()),
    path('organization/<uuid:pk>/', listOrgProjectsView.as_view()),
    path('<uuid:pk>/donations/', ListDonationsView.as_view()),
    path('<uuid:pk>/comments/', listCommentsByProjectsView.as_view()),
    path('<uuid:pk>/comments/add/', CommentCreateView.as_view()),
    path('<uuid:pk>/post-update/', PostUpdateView.as_view()),
    path('comments/<uuid:pk>/', CommentRetrieveUpdateDestroyView.as_view()),
    path('milestones/<uuid:pk>/', MilestoneRetrieveView.as_view()),
    path('milestones/<uuid:pk>/post-images/', PostMilestoneImages.as_view()),
    path('milestones/<uuid:pk>/add-expenses/', ExpensesCreateView.as_view()),
    path('milestones/images/<uuid:pk>/', MilestoneImagesRetrieveUpdateDestroyAPIView.as_view()),
    path('<uuid:pk>/donate/', MakeDonationsAPIView.as_view()),
]
