# Generated by Django 5.2.1 on 2025-06-30 18:15

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_no', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('details', tinymce.models.HTMLField(null=True)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('Waiting for Report', 'Waiting for Report'), ('Not Started', 'Not Started'), ('Implemented', 'Implemented')], default='Not Started', max_length=25)),
                ('funds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof_pdf_url', models.URLField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('country', models.CharField(max_length=30)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=65, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=65, null=True)),
                ('image_url', models.URLField()),
                ('description', tinymce.models.HTMLField(null=True)),
                ('problem_to_address', tinymce.models.HTMLField(null=True)),
                ('solution', tinymce.models.HTMLField(null=True)),
                ('summary', tinymce.models.HTMLField(null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('FLAGGED', '🚩FLAGGED'), ('PENDING', 'PENDING'), ('✅APPROVED', '✅APPROVED'), ('❌DISAPPROVED', '❌DISAPPROVED')], default='PENDING', max_length=20)),
                ('approverd_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action_by', models.CharField(max_length=30, null=True)),
                ('reason', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Funding', 'Funding'), ('Under Implementation', 'Under Implementation'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Funding', max_length=20)),
                ('ended_at', models.DateTimeField(null=True)),
                ('total_funds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('categories', models.ManyToManyField(related_name='projects', to='projects.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project'),
        ),
    ]
