# Generated by Django 5.2.1 on 2025-07-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='milestone_images',
            old_name='image',
            new_name='image_url',
        ),
    ]
