# Generated by Django 5.2.1 on 2025-07-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
