# Generated by Django 5.2.1 on 2025-07-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_user_profile_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone_images',
            name='img_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='img_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='img_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
