# Generated by Django 5.2.1 on 2025-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_milestone_images_img_public_id_project_img_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pdf_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
