# Generated by Django 5.2.1 on 2025-07-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_expense_pdf_public_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestone_Images',
            new_name='MilestoneImage',
        ),
    ]
