# Generated by Django 5.2.1 on 2025-07-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
